Borrador
Jalejandrojb/Tablero-de-Ludo pull request #1
Opened 2020-08-02 19:29 UTC by Jalejandrojb

Oh, no. El codigo ya no esta orientado a objetos

2020-08-02 20:24 UTC, jjimenez22 commented
Vas a tener que resolver esos conflictos. Y ponerle un titulo mas descriptivo

2020-08-02 21:19 UTC, jjimenez22 requested changes

2020-08-02 21:19 UTC, jjimenez22 commented on README.md
> +3. Dar click al dado para tirarlo (dar mas de un click buguea el tablero)
Deberias poner un todo en el codigo donde deberia estar el fix de este bug, y eventualmente hacer un fix

2020-08-02 21:19 UTC, jjimenez22 commented on scripts.js
> +{}, {}, {}, {}]
```suggestion
const casilla = Array(52).fill({})
```
Oh no recuerda, siempre que la tarea es repetitiva seguro hay una mejor forma de hacerla

2020-08-02 21:19 UTC, jjimenez22 commented on scripts.js
> +const casillaVerde = [{}, {}, {}, {}, {}]
Lo mismo que la correccion anterior, pero esto si te dejo que tu mismo lo corrijas

2020-08-02 21:19 UTC, jjimenez22 commented on scripts.js
> +	color: 'blue',
Es curioso como nombraste todas las variables en español cuando se recomienda ingles, pero los valores literales que da igual el idioma si los pusiste en ingles  :thinking:

2020-08-02 21:19 UTC, jjimenez22 commented on scripts.js
> +			break;
Esto se puede mejorar simulando una estructura tipo [cola circular](https://es.wikipedia.org/wiki/Cola_circular#:~:text=Una%20cola%20circular%20o%20anillo,un%20sucesor%20y%20un%20predecesor.) para hacer un [round robin](https://es.wikipedia.org/wiki/Planificaci%C3%B3n_Round-robin) entre los jugadores. Asi te evitas la variable de turno y el case. Esto es mejor dejarlo para futuro en su propio branch

2020-08-02 21:19 UTC, jjimenez22 commented on scripts.js
> +		jugador.ficha4.removeEventListener('click', habilitar4)
Esto es medio feo, si vas a tener variables 1, 2, 3 y 4 es mejor tener arrays de fichas y habilitar de tamaño 4 y llamar a un foreach `jugador.fichas.foreach((f,i)=>f.removeEventListener('click',habilitar[i]))`

2020-08-02 21:19 UTC, jjimenez22 commented on scripts.js
> +	const habilitar4 = () => sacarFicha(jugador.ficha4)			//a sacar ficha
Aqui igual que en la anterior, puedes guardar esas funciones en un array

2020-08-02 21:19 UTC, jjimenez22 commented on scripts.js
> +	jugador.ficha4.addEventListener('click', habilitar4)
Aqui igual

2020-08-02 21:19 UTC, jjimenez22 commented on scripts.js
> +	const obtenerCasillaBlanca = (e, i, arr) => {						//callbacks para 'forEach()'
Oh no no hace falta pasar el array como argumento, es mejor hacer un foreach `arr.foreach((e, i)=>{...})`

2020-08-02 21:19 UTC, jjimenez22 commented on scripts.js
> +		arr[i].fichasPuesto4 = []
Bueno y creo que tu mismo puedes buscar todas las partes en las que puedes cambiar variables por arrays con las correcciones de mas arriba

2020-08-03 20:22 UTC, Jalejandrojb commented on scripts.js
> +{}, {}, {}, {}]
oh, no. ya había probado hacerlo así antes, y no funciono como lo esperaba:
Por lo que pude apreciar, al llenar el arreglo de esa manera con un objeto, se llena con algo parecido a apuntadores que apuntan a un mismo objeto. Entonces, cualquier cambio que se la haga a cualquier elemento del arreglo, se hace en cada elemento del arreglo (lo que sospecho que son apuntadores al mismo objeto, y son, de hecho, cambios a un solo objeto). Por eso lo he terminado haciendo de esa forma tan engorrosa

2020-08-03 20:25 UTC, Jalejandrojb commented on scripts.js
> +	color: 'blue',
Lo que pasa es que con ese valor literal planeo agregar estilos de diferentes colores mas adelante, y tenia entendido que en CSS solo entiende ingles.
Hay alguna forma mas practica de hacerlo?

2020-08-03 20:46 UTC, Jalejandrojb commented on scripts.js
> +	const obtenerCasillaBlanca = (e, i, arr) => {						//callbacks para 'forEach()'
oh, no. y luego como me refiero al arreglo dentro del callback que va a correr forEach?

2020-08-27 19:09 UTC, merged

2020-08-28 00:59 UTC, jjimenez22 commented
Oh no mergeaste sin que te aprobara

2020-08-28 01:07 UTC, jjimenez22 commented on scripts.js
> +	const obtenerCasillaBlanca = (e, i, arr) => {						//callbacks para 'forEach()'
Tengo que googlear, en el foreach tambien puede pasar el array como argumento, o sea pasarse a si mismo como argumento de su foreach. Tambien en teoria si estas llamando al foreach obviamente tienes al array ahi, que sigue teniendo alcance dentro del ambito del foreach

2020-08-28 01:07 UTC, jjimenez22 commented on scripts.js
> +	color: 'blue',
Bueno la verdad de css no te se decir buenas practicas, hay que preguntarle a geral